name: main

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: pcov
        tools: phpstan, php-cs-fixer:3

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install
      uses: "ramsey/composer-install@v2"

    - name: Run PHP CS Fixer
      run: php-cs-fixer fix --diff --dry-run

    - name: Run PHPStan
      run: phpstan analyse src
